### ISSUE TITLE
undefined symbol: dense_multiexp

### ISSUE THREAD

**Issue by druiz0992** [matter-labs/belle_cuda#1]
Hello,

I am trying to use this repo to benchmark different SNARK provers on GPUs.  After launching the test as described in README, i get the error below. 

Thanks

----

cargo test --release -- --nocapture test_mimc_bn256_gpu_all
    Finished release [optimized] target(s) in 0.19s
     Running target/release/deps/bellman_ce-9c5ab40de88a6857

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 11 filtered out

     Running target/release/deps/mimc-ae4b0d4793d503aa
/local/david/iden3/matterlabs/bellman/target/release/deps/mimc-ae4b0d4793d503aa: symbol lookup error: /local/david/iden3/matterlabs/bellman/target/release/deps/mimc-ae4b0d4793d503aa: undefined symbol: dense_multiexp
error: test failed, to rerun pass '--test mimc'

**Comment by shamatar** [comment]
Did you compile and copy the `libcuda.so` file to the root of the `bellman` directory?

**Comment by druiz0992** [comment]
yes, I did. 

I verified correct build by removing libcuda.so and it failed as expected. When libcuda.so is present in root bellman folder, build completes, but launching test produces the error.

**Comment by druiz0992** [comment]
By the way, I am using cmake 3.15.2 and GNU make 4.1

**Comment by saladsilica** [comment]
Hi @druiz0992, I was having the same issue, the build works but to run the test you need to add `LD_LIBRARY_PATH=.` to the `cargo` command.

**Comment by druiz0992** [comment]
Thanks. That worked for me!!
